### ISSUE TITLE
sails lift fails as gulp seems to be missing from sails node_modules directory

### ISSUE THREAD

**Issue by pschuegr** [Karnith/sails-generate-new-gulp#5]
Hi, I cannot start the app after following your setup instructions.

```
ls -al node_modules

lrwxr-xr-x   1 pschuegr  staff    60 20 Mar 14:45 gulp -> /Users/pschuegr/npm/lib/node_modules/sails/node_modules/gulp
```

gulp does not exist in this location.  any suggestions?  the gulpfile was generated correctly.

Thanks!

**Comment by pschuegr** [comment]
So, because sails depends on grunt, when using gulp, it seems to symlink to the sails/node_modules/grunt because it knows it will be there.  With the gulp version, it symlinks even though it actually isn't there.  npm install fixed this.

**Comment by Karnith** [comment]
Grunt shouldn't be needed. I'll have a look when I have time, but unless they made some massive changes to sails the generators should still work. What are the steps you took to install and configure?

**Comment by pschuegr** [comment]
I think sails has grunt in its package.json, so it's automatically installed when sails is installed.  

I literally followed your installation instructions from the README.  Globally install the generate-gulp packages and create the .sailsrc.

After I did ```sails new app``` and went to app and ran ```npm install```, it installed the gulp plugins, so everything worked after that.
