### ISSUE TITLE
Watch asset directories instead of entire folder

### ISSUE THREAD

**Issue by Ehesp** [Karnith/sails-generate-new-gulp#6]
Hello

From what I can gather, while running via development, the `default.js` task triggers the `watch:assets` task... which is:

```
	gulp.task('watch:assets', function() {
		// Watch assets
		return gulp.watch(['assets/**/*', 'tasks/pipeline.js'], ['syncAssets'])
				.on('change', function(file) {
					server.changed(file.path);
				});
	});
```

On a large project, with loads of scripts, images and other things changing a single file is causing the entire folder to be synced which is causing poor performance (the main reason I moved from Grunt).

Surely it'd be more performance efficient to watch individual directories (`assets/js`, `assets/styles`, `assets/images`) and then run tasks specifically against them. I'm having to wait 5-10 seconds on every save right now.

Cheers

**Comment by Karnith** [comment]
Hi,

The tasks are fully configurable. To get this to work how your example shows, change

gulp.watch(['assets/**/*', 'tasks/pipeline.js'], ['syncAssets'])

To

gulp.watch(['assets/styles/*', 'assets/js/*',  'assets/images/*', 'tasks/pipeline.js'], ['syncAssets'])

for the desired functionality. The tasks are really just configured with a default set of parameters and it is expected to be changed based off individual needs.

~Karnith


-------- Original message --------
