### ISSUE TITLE
Fix Deprecation Warnings

### ISSUE THREAD

**Issue by kevintechie** [Karnith/sails-generate-new-gulp#9]
Generating a new project and then 'sails lift' causes deprication warnings:

debug: Deprecation warning: Support for `sails.config.sockets.onConnect` will be removed in an upcoming release. See the v0.11 migration guide for more information and alternate options.
debug: Deprecation warning: `sails.config.sockets.onDisconnect` is now `sails.config.sockets.afterDisconnect`
Setting it for you this time, but note that the new `afterDisconnect` now receives an additional final argument (a callback).
More info: http://sailsjs.org/#!/documentation/reference/sails.config/sails.config.sockets.html

**Comment by Karnith** [comment]
Hi, I'm currently in the process of updating all the generators and creating machine packs of them.

-------- Original message --------

**Comment by kevintechie** [comment]
Nice. Thanks.

**Comment by netlander** [comment]
I am using the gulp generator from npm repository using:

```
$ npm install -g sails-generate-backend-gulp
$ npm install -g sails-generate-gulpfile
$ npm install -g sails-generate-frontend-gulp
$ npm install -g sails-generate-new-gulp

```

and getting the deprecation warnings:

```
warn: `sails.config.sockets.onConnect` has been deprecated, and support will be removed in an upcoming release. See the v0.11 migration guide for more information.
warn: (running it for you this time)
```

I'm also getting these warnings, not sure if they're related to the same issue:

```
warn: Socket disconnected, but session could not be loaded to pass to configured disconnect handler: `sails.config.sockets.afterDisconnect()`.  Will pass a fake, empty session as argument to lifecycle callback.  Details:
 Error: Session could not be loaded
    at _createError (C:\Users\maste_000\AppData\Roaming\npm\node_modules\sails\lib\hooks\session\index.js:271:21)
    at Immediate.<anonymous> (C:\Users\maste_000\AppData\Roaming\npm\node_modules\sails\lib\hooks\session\index.js:274:13)
    at Immediate.immediate._onImmediate (timers.js:425:18)
    at processImmediate [as _immediateCallback] (timers.js:368:17) { [Error: Session could not be loaded] code: 'E_SESSION' }

```

Should I be looking at downloading from a different location?

**Comment by Karnith** [comment]
@netlander Hi, yes the new module is [machinepack-sailsgulpify](https://github.com/Karnith/machinepack-sailsgulpify) https://github.com/Karnith/machinepack-sailsgulpify

**Comment by netlander** [comment]
But do you use this in an empty folder or a newly generated sails project?

**Comment by Karnith** [comment]
a newly generated sails project, or existing sails project should work also.

**Comment by Karnith** [comment]
the machinepack is added via npm, so there needs to be an existing project first.

**Comment by netlander** [comment]
Thanks
